apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: github-tekon-quay-quarkus-14-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/github-tekon-quay-quarkus-14